package ec.edu.espe.evsustore.view;



import ec.edu.espe.evsustore.controller.HardwareComponentController;
import ec.edu.espe.evsustore.controller.ViewController;
import java.awt.BorderLayout;
import java.util.HashMap;
import javax.swing.JPanel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Joan Cobeña, KillChain, DCCO-ESPE
 */
public class PnelViewInventory extends javax.swing.JPanel {

    HardwareComponentController componentController = HardwareComponentController.getInstance();
    
    
    public PnelViewInventory( ) {
        initComponents();
        
        displayComponentsTable();
        addListeners();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnelViewInfo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblComponents = new javax.swing.JTable();
        pnelTableButtons = new javax.swing.JPanel();
        btnRefreshTable = new javax.swing.JButton();
        txtSearchBar = new javax.swing.JTextField();
        btnBacktToInventoryMenu = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        Content.setBackground(new java.awt.Color(18, 9, 24));
        Content.setForeground(new java.awt.Color(18, 9, 24));
        Content.setPreferredSize(new java.awt.Dimension(900, 675));

        tblComponents.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tblComponents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cantidad", "Nombre", "Modelo", "Costo", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblComponents.setMaximumSize(new java.awt.Dimension(300, 25));
        tblComponents.setOpaque(false);
        tblComponents.setRowHeight(25);
        tblComponents.setSelectionBackground(new java.awt.Color(169, 104, 216));
        tblComponents.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblComponents.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblComponents.getTableHeader().setReorderingAllowed(false);
        tblComponents.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblComponentsPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblComponents);

        javax.swing.GroupLayout pnelViewInfoLayout = new javax.swing.GroupLayout(pnelViewInfo);
        pnelViewInfo.setLayout(pnelViewInfoLayout);
        pnelViewInfoLayout.setHorizontalGroup(
            pnelViewInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnelViewInfoLayout.setVerticalGroup(
            pnelViewInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pnelTableButtons.setBackground(new java.awt.Color(18, 9, 24));

        btnRefreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTableActionPerformed(evt);
            }
        });

        txtSearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchBarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnelTableButtonsLayout = new javax.swing.GroupLayout(pnelTableButtons);
        pnelTableButtons.setLayout(pnelTableButtonsLayout);
        pnelTableButtonsLayout.setHorizontalGroup(
            pnelTableButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnelTableButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefreshTable, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        pnelTableButtonsLayout.setVerticalGroup(
            pnelTableButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnelTableButtonsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnelTableButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRefreshTable, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(txtSearchBar))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnBacktToInventoryMenu.setBackground(new java.awt.Color(133, 44, 194));
        btnBacktToInventoryMenu.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnBacktToInventoryMenu.setText("Volver al Menú de Inventario");
        btnBacktToInventoryMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBacktToInventoryMenuActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(133, 44, 194));
        btnDelete.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnDelete.setText("Borrar");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(133, 44, 194));
        btnUpdate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnUpdate.setText("Actualizar");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addComponent(pnelTableButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnelViewInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(ContentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126)
                .addComponent(btnBacktToInventoryMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addComponent(pnelTableButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnelViewInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnBacktToInventoryMenu))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        HashMap<Object, Object> selectedComponent = getSelectedComponent();
        PnelSaveHardwareComponent frmComponentToUpdate = new PnelSaveHardwareComponent((int)selectedComponent.get("id"));
        showPanel(frmComponentToUpdate);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        HashMap<Object, Object> selectedComponent = getSelectedComponent();
        componentController.delete(selectedComponent);
        displayComponentsTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblComponentsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblComponentsPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tblComponentsPropertyChange

    private void btnRefreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTableActionPerformed
        displayComponentsTable();
    }//GEN-LAST:event_btnRefreshTableActionPerformed

    private void btnBacktToInventoryMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBacktToInventoryMenuActionPerformed
        PnelInventory pnelInventory=new PnelInventory();
        showPanel(pnelInventory);
    }//GEN-LAST:event_btnBacktToInventoryMenuActionPerformed

    private void txtSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchBarActionPerformed
    
    private void addListeners(){
        TableRowSorter rowSorter = new TableRowSorter(tblComponents.getModel());
        tblComponents.setRowSorter(rowSorter);
        SearchBarListener searchBarListener = new SearchBarListener(tblComponents, txtSearchBar);
        txtSearchBar.getDocument().addDocumentListener(searchBarListener);
    }
    
    private void showPanel(JPanel panelUI) {
        panelUI.setSize(900, 675);
        panelUI.setLocation(0, 0);
        Content.removeAll();
        Content.add(panelUI, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }
    
    private HashMap<Object, Object> getSelectedComponent() {
        int selectedRowIndex = tblComponents.getSelectedRow();
        int id = (int) tblComponents.getValueAt(selectedRowIndex, 0);
        HashMap<Object, Object> selectedComponent = componentController.obtainFromDb(id);
        return selectedComponent;
    }
    
    public void displayComponentsTable(){
        ViewController.displayTable(tblComponents, componentController.obtainAllFromDb());
    
        TableColumnModel tblColumnModel = tblComponents.getColumnModel();
        
        tblColumnModel.moveColumn(5, 1);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JButton btnBacktToInventoryMenu;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefreshTable;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnelTableButtons;
    private javax.swing.JPanel pnelViewInfo;
    private javax.swing.JTable tblComponents;
    private javax.swing.JTextField txtSearchBar;
    // End of variables declaration//GEN-END:variables
}
